version: '3'
# this a demonstration docker-compose, not for production.
services:
  api: 
    build: .
    command: bash -c "gunicorn egdocketsearch.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "${SECRET_KEY}"